# Generated by Django 5.0.9 on 2024-10-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PageVisiti",
            new_name="PageVisitis",
        ),
    ]
